spring.application.name=certiVault

server.port = 8081

spring.datasource.url=jdbc:postgresql://localhost:5432/certivault
spring.datasource.username=sv_user
spring.datasource.password=sv_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# IPFS config (custom)
ipfs.api.url=http://localhost:5001

